### ISSUE TITLE
Precompilation fails on `@agent`

### ISSUE THREAD

**Issue by zenna** [JuliaDynamics/Agents.jl#409] opened 2021-02-03 22:27 UTC
**Describe the bug**
Precompilation fails on simple examples which uses `@agent Zombie OSMAgent` 

**Minimal Working Example**
1. Generate a new package `TestAgents`
2. Replace TestAgents.jl with:

```julia
module TestAgents

using Agents
@agent Zombie OSMAgent begin
  infected::Bool
end

end # module
```

Then try `using TestAgents`

**Agents.jl version**
 Agents v4.0.4
Julia 1.5.3

**Comment by Libbum** [comment] 2021-02-03 22:47
Hmm. I can't reproduce this. Can you send me `] st` and `] st -m`?

**Comment by Libbum** [comment] 2021-02-04 08:14
OK, I've taken another look and managed to get it to fail. Will take a look at the issue soon.

**Comment by Libbum** [comment] 2021-02-04 09:32
The problem lies with [this eval](/home/tim/.julia/packages/Agents/symzu/src/core/agents.jl) call. I tried to make the call global in [this branch](https://github.com/JuliaDynamics/Agents.jl/tree/module_wrap), but the issue still occurs. Will check with some of the more competent metaprogramming people to see if there's a solution to this problem. 

For the moment you can move ahead with your project by using the full struct which the macro would build for you here:
```julia
mutable struct Zombie <: AbstractAgent
      id::Int64
      pos::Tuple{Int64,Int64,Float64}
      route::Array{Int64,1}
      destination::Tuple{Int64,Int64,Float64}
      infected::Bool
end
```

**Comment by trevorgrif** [comment] 2022-10-16 03:32
Bug still exist on v5.4.3.

**Comment by Tortar** [comment] 2023-04-15 23:45
I managed to get it to fail in 5.4.3 as @trevorgrif reported, but **not** on 5.14.0, the agent macro has been rewritten somewhat between this two versions and the modifications apparently solved the problem. So I think it's safe to close the issue now

**Closed by Tortar** 2023-04-15 23:45 UTC
Labels: bug
