### ISSUE TITLE
Cannot reproduce Zombie outbreak

### ISSUE THREAD

**Issue by jgamper** [JuliaDynamics/Agents.jl#620] opened 2022-04-29 21:40 UTC
When attempting to reproduce the Zombie Outbreak example, at exactly the last step:

```
using InteractiveDynamics
using CairoMakie
CairoMakie.activate!() 
ac(agent) = agent.infected ? :green : :black
as(agent) = agent.infected ? 10 : 8
model = initialise()

abmvideo("outbreak.mp4", model, agent_step!;
title = "Zombie outbreak", framerate = 15, frames = 200, as, ac)
```

I get the following error:

```
MethodError: no method matching keys(::Base.Generator{Vector{Int64}, OSMMakie.var"#20#22"{Vector{Int64}}})
Closest candidates are:
  keys(!Matched::Union{Tables.AbstractColumns, Tables.AbstractRow}) at /Users/me/.julia/packages/Tables/PxO1m/src/Tables.jl:184
  keys(!Matched::Missings.EachReplaceMissing) at /Users/me/.julia/packages/Missings/r1STI/src/Missings.jl:94
  keys(!Matched::DataStructures.SortedDict) at /Users/me/.julia/packages/DataStructures/vSp4s/src/container_loops.jl:233
  ...

Stacktrace:
  [1] pairs(collection::Base.Generator{Vector{Int64}, OSMMakie.var"#20#22"{Vector{Int64}}})
    @ Base ./abstractdict.jl:138
  [2] _findmax(a::Base.Generator{Vector{Int64}, OSMMakie.var"#20#22"{Vector{Int64}}}, #unused#::Colon)
    @ Base ./array.jl:2243
  [3] findmax(a::Base.Generator{Vector{Int64}, OSMMakie.var"#20#22"{Vector{Int64}}})
    @ Base ./array.jl:2240
  [4] size_nodes(gpk::Attributes, osm::LightOSM.OSMGraph{Int32, Int64, Float64}, sorted_edges::Vector{Vector{UInt16}}, edge_width::Vector{Int64})
    @ OSMMakie ~/.julia/packages/OSMMakie/dXQe5/src/defaults/defaults.jl:57
  [5] set_node_defaults(osmplot::Combined{OSMMakie.osmplot, Tuple{LightOSM.OSMGraph{Int32, Int64, Float64}}}, edge_width::Vector{Int64}, edge_color::Vector{ColorTypes.RGB{FixedPointNumbers.N0f8}})
    @ OSMMakie ~/.julia/packages/OSMMakie/dXQe5/src/defaults/defaults.jl:37
  [6] plot!(osmplot::Combined{OSMMakie.osmplot, Tuple{LightOSM.OSMGraph{Int32, Int64, Float64}}})
    @ OSMMakie ~/.julia/packages/OSMMakie/dXQe5/src/recipe.jl:69
  [7] plot!(scene::Scene, P::Type{Combined{OSMMakie.osmplot, Tuple{LightOSM.OSMGraph{Int32, Int64, Float64}}}}, attributes::Attributes, input::Tuple{Observable{LightOSM.OSMGraph{Int32, Int64, Float64}}}, args::Observable{Tuple{LightOSM.OSMGraph{Int32, Int64, Float64}}})
    @ Makie ~/.julia/packages/Makie/lgPZh/src/interfaces.jl:401
  [8] plot!(scene::Scene, P::Type{Combined{OSMMakie.osmplot, ArgType} where ArgType}, attributes::Attributes, args::LightOSM.OSMGraph{Int32, Int64, Float64}; kw_attributes::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie ~/.julia/packages/Makie/lgPZh/src/interfaces.jl:319
  [9] plot!(scene::Scene, P::Type{Combined{OSMMakie.osmplot, ArgType} where ArgType}, attributes::Attributes, args::LightOSM.OSMGraph{Int32, Int64, Float64})
    @ Makie ~/.julia/packages/Makie/lgPZh/src/interfaces.jl:287
 [10] plot!(la::Axis, P::Type{Combined{OSMMakie.osmplot, ArgType} where ArgType}, attributes::Attributes, args::LightOSM.OSMGraph{Int32, Int64, Float64}; kw_attributes::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie.MakieLayout ~/.julia/packages/Makie/lgPZh/src/makielayout/layoutables/axis.jl:693
 [11] plot!
    @ ~/.julia/packages/Makie/lgPZh/src/makielayout/layoutables/axis.jl:688 [inlined]
 [12] plot!(P::Type{Combined{OSMMakie.osmplot, ArgType} where ArgType}, ax::Axis, args::LightOSM.OSMGraph{Int32, Int64, Float64}; kw_attributes::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie.MakieLayout ~/.julia/packages/Makie/lgPZh/src/makielayout/layoutables/axis.jl:705
 [13] plot!(P::Type{Combined{OSMMakie.osmplot, ArgType} where ArgType}, ax::Axis, args::LightOSM.OSMGraph{Int32, Int64, Float64})
    @ Makie.MakieLayout ~/.julia/packages/Makie/lgPZh/src/makielayout/layoutables/axis.jl:704
 [14] osmplot!(::Axis, ::Vararg{Any, N} where N; attributes::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ OSMMakie ~/.julia/packages/MakieCore/A0hGm/src/recipes.jl:37
 [15] osmplot!(::Axis, ::Vararg{Any, N} where N)
    @ OSMMakie ~/.julia/packages/MakieCore/A0hGm/src/recipes.jl:37
 [16] plot!(abmplot::Combined{InteractiveDynamics._abmplot, Tuple{AgentBasedModel{Agents.OSM.OpenStreetMapSpace, Zombie, typeof(Agents.Schedulers.fastest), Dict{Symbol, Float64}, MersenneTwister}}})
    @ InteractiveDynamics ~/.julia/packages/InteractiveDynamics/QEgSa/src/agents/abmplot.jl:223
 [17] plot!(scene::Scene, P::Type{Combined{InteractiveDynamics._abmplot, Tuple{AgentBasedModel{Agents.OSM.OpenStreetMapSpace, Zombie, typeof(Agents.Schedulers.fastest), Dict{Symbol, Float64}, MersenneTwister}}}}, attributes::Attributes, input::Tuple{Observable{AgentBasedModel{Agents.OSM.OpenStreetMapSpace, Zombie, typeof(Agents.Schedulers.fastest), Dict{Symbol, Float64}, MersenneTwister}}}, args::Observable{Tuple{AgentBasedModel{Agents.OSM.OpenStreetMapSpace, Zombie, typeof(Agents.Schedulers.fastest), Dict{Symbol, Float64}, MersenneTwister}}})
    @ Makie ~/.julia/packages/Makie/lgPZh/src/interfaces.jl:401
 [18] plot!(scene::Scene, P::Type{Combined{InteractiveDynamics._abmplot, ArgType} where ArgType}, attributes::Attributes, args::AgentBasedModel{Agents.OSM.OpenStreetMapSpace, Zombie, typeof(Agents.Schedulers.fastest), Dict{Symbol, Float64}, MersenneTwister}; kw_attributes::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie ~/.julia/packages/Makie/lgPZh/src/interfaces.jl:319
 [19] plot!(scene::Scene, P::Type{Combined{InteractiveDynamics._abmplot, ArgType} where ArgType}, attributes::Attributes, args::AgentBasedModel{Agents.OSM.OpenStreetMapSpace, Zombie, typeof(Agents.Schedulers.fastest), Dict{Symbol, Float64}, MersenneTwister})
    @ Makie ~/.julia/packages/Makie/lgPZh/src/interfaces.jl:287
 [20] plot!(la::Axis, P::Type{Combined{InteractiveDynamics._abmplot, ArgType} where ArgType}, attributes::Attributes, args::AgentBasedModel{Agents.OSM.OpenStreetMapSpace, Zombie, typeof(Agents.Schedulers.fastest), Dict{Symbol, Float64}, MersenneTwister}; kw_attributes::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Makie.MakieLayout ~/.julia/packages/Makie/lgPZh/src/makielayout/layoutables/axis.jl:693
 [21] plot!
    @ ~/.julia/packages/Makie/lgPZh/src/makielayout/layoutables/axis.jl:688 [inlined]
 [22] #plot!#336
    @ ~/.julia/packages/Makie/lgPZh/src/makielayout/layoutables/axis.jl:705 [inlined]
 [23] _abmplot!(::Axis, ::Vararg{Any, N} where N; attributes::Base.Iterators.Pairs{Symbol, Any, NTuple{6, Symbol}, NamedTuple{(:ax, :abmobs, :add_controls, :_add_interaction, :as, :ac), Tuple{Axis, ABMObservable{AgentBasedModel{Agents.OSM.OpenStreetMapSpace, Zombie, typeof(Agents.Schedulers.fastest), Dict{Symbol, Float64}, MersenneTwister}, typeof(dummystep), typeof(dummystep), Nothing, Nothing, Nothing, Nothing, Bool}, Bool, Bool, typeof(as), typeof(ac)}}})
    @ InteractiveDynamics ~/.julia/packages/MakieCore/A0hGm/src/recipes.jl:37
[24] abmplot!(ax::Axis, model::AgentBasedModel{Agents.OSM.OpenStreetMapSpace, Zombie, typeof(Agents.Schedulers.fastest), Dict{Symbol, Float64}, MersenneTwister}; agent_step!::Function, model_step!::Function, adata::Nothing, mdata::Nothing, when::Bool, _add_interaction::Bool, add_controls::Bool, enable_inspection::Bool, kwargs::Base.Iterators.Pairs{Symbol, Function, Tuple{Symbol, Symbol}, NamedTuple{(:as, :ac), Tuple{typeof(as), typeof(ac)}}})
    @ InteractiveDynamics ~/.julia/packages/InteractiveDynamics/QEgSa/src/agents/abmplot.jl:134
 [25] abmvideo(file::String, model::AgentBasedModel{Agents.OSM.OpenStreetMapSpace, Zombie, typeof(Agents.Schedulers.fastest), Dict{Symbol, Float64}, MersenneTwister}, agent_step!::typeof(agent_step!), model_step!::typeof(dummystep); spf::Int64, framerate::Int64, frames::Int64, title::String, showstep::Bool, figure::NamedTuple{(), Tuple{}}, axis::NamedTuple{(), Tuple{}}, kwargs::Base.Iterators.Pairs{Symbol, Function, Tuple{Symbol, Symbol}, NamedTuple{(:as, :ac), Tuple{typeof(as), typeof(ac)}}})
    @ InteractiveDynamics ~/.julia/packages/InteractiveDynamics/QEgSa/src/agents/convenience.jl:141
 [26] top-level scope
    @ ~/Dropbox/Projects/ridesharing-simulation/lightosm.ipynb:8
 [27] eval
    @ ./boot.jl:360 [inlined]
 [28] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:1116
 [29] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
 [30] invokelatest
    @ ./essentials.jl:706 [inlined]
 [31] (::VSCodeServer.var"#160#161"{VSCodeServer.NotebookRunCellArguments, String})()
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.6.17/scripts/packages/VSCodeServer/src/serve_notebook.jl:19
 [32] withpath(f::VSCodeServer.var"#160#161"{VSCodeServer.NotebookRunCellArguments, String}, path::String)
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.6.17/scripts/packages/VSCodeServer/src/repl.jl:184
 [33] notebook_runcell_request(conn::VSCodeServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::VSCodeServer.NotebookRunCellArguments)
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.6.17/scripts/packages/VSCodeServer/src/serve_notebook.jl:13
 [34] dispatch_msg(x::VSCodeServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::VSCodeServer.JSONRPC.MsgDispatcher, msg::Dict{String, Any})
    @ VSCodeServer.JSONRPC ~/.vscode/extensions/julialang.language-julia-1.6.17/scripts/packages/JSONRPC/src/typed.jl:67
 [35] serve_notebook(pipename::String, outputchannel_logger::Base.CoreLogging.SimpleLogger; crashreporting_pipename::String)
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.6.17/scripts/packages/VSCodeServer/src/serve_notebook.jl:136
 [36] top-level scope
    @ ~/.vscode/extensions/julialang.language-julia-1.6.17/scripts/notebook/notebook.jl:32
 [37] include(mod::Module, _path::String)
    @ Base ./Base.jl:384
 [38] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:285
 [39] _start()
    @ Base ./client.jl:485
```

**Agents.jl version**

Agents v5.2.0

**Comment by Datseris** [comment] 2022-04-30 06:33
`InteractiveDynamics` version = ?

**Comment by jgamper** [comment] 2022-04-30 12:51
@Datseris it's InteractiveDynamics v0.21.1

**Comment by Datseris** [comment] 2022-04-30 13:15
I cannot reproduce your problem. May try making a Minimal Working Example as expected by the issue template? The example online works fine, otherwise you wouldn't be seeing any images: https://juliadynamics.github.io/Agents.jl/stable/examples/zombies/  . So I can't just take that code and try to reproduce your problem.

**Comment by jgamper** [comment] 2022-04-30 13:20
Thanks! Could it be because of Julia version 1.6.6? 

I wonder what a Minimal Working Example would be, I simply took the zombie apocalypsis example line by line :(

**Comment by Datseris** [comment] 2022-05-01 07:38
From the error message, this looks like `OSMMakie`-related (cc @fbanning ). What's your `OSMMakie` version?

The Minimal Working Example would be the smallest code snippet that when run it produces your problem. If you just used the online zombies example, just take that code, and remove all the parts not necessary to reach your problem, and then report it here.

**Comment by jgamper** [comment] 2022-05-01 20:04
> From the error message, this looks like `OSMMakie`-related (cc @fbanning ). What's your `OSMMakie` version?

@Datseris it is OSMMakie v0.0.4

**Comment by jgamper** [comment] 2022-05-01 20:14
I suppose this would be the Minimal Working Example? Running this I get exactly the same MethodError as mentioned in my first message.

```
using Agents
using Random

mutable struct Zombie <: AbstractAgent
    id::Int
    pos::Tuple{Int, Int, Float64}
    infected::Bool
    speed::Float64
end

function initialise(; seed = 1234)
    # map_path = "/Users/jevgenijgamper/Dropbox/Projects/ridesharing-simulation/vilnius.json"
    map_path = OSM.test_map()
    properties = Dict(:dt => 1/60)
    model = ABM(
        Zombie,
        OpenStreetMapSpace(map_path),
        properties=properties,
        rng = Random.MersenneTwister(seed)
    )
    return model
end

function agent_step!(agent, model)
end

using InteractiveDynamics
using CairoMakie
CairoMakie.activate!() 
ac(agent) = agent.infected ? :green : :black
as(agent) = agent.infected ? 10 : 8
model = initialise()

abmvideo("outbreak.mp4", model, agent_step!;
title = "Zombie outbreak", framerate = 15, frames = 200, as, ac)
```

**Comment by Datseris** [comment] 2022-05-01 21:22
Once again I unfortunately cannot reproduce your problem. I run the above code snippet without any problems.

**Comment by fbanning** [comment] 2022-05-02 09:06
> Could it be because of Julia version 1.6.6?

Oof, I'm not sure here. Have you tried to reproduce your problem with Julia 1.7.x?

**Comment by jgamper** [comment] 2022-05-02 12:21
> Have you tried to reproduce your problem with Julia 1.7.x?

- tried with Julia 1.5.4 and then realised that OSMMakie only supports 1.6 and 1.7 https://github.com/fbanning/OSMMakie.jl/blob/35c13b08179cb8535a8f417994a8048de675b443/Project.toml#L13

- tried with 1.7.2 and it works

- the issue seems to be 1.6 specific

**Comment by Datseris** [comment] 2022-05-02 12:53
I think we need to add tests and CI in OSMMakie.jl, I just saw it doesn't have any so we couldn't detect this automatically.

**Comment by Datseris** [comment] 2022-05-02 12:54
(problem is of course, I do not know how to really "test" plotting packages. Thankfully here we only need to call `osmplot` with CairoMakie and test that it doesn't error)

**Comment by fbanning** [comment] 2022-06-09 11:06
OK, I've found the culprit. I've been using `findmax` which is only supported from Julia 1.7 onwards. I'll search for a good workaround. This issue should be fixed with the upcoming 0.0.5 release. It's due soon ™️ .

On a sidenote: I'm currently adding some basic tests to avoid these things from happening again.

**Comment by fbanning** [comment] 2022-06-09 11:54
@Datseris As I don't have write access, you can assign me to this issue if you want and also remove the `can't reproduce` tag because it is indeed reproducible on Julia 1.6.

**Comment by fbanning** [comment] 2022-06-13 15:47
[OSMMakie 0.0.5 has just been released.](https://github.com/fbanning/OSMMakie.jl/releases/tag/v0.0.5) Please try it out and tell me if this error persists on your end. Otherwise, I would consider this issue closed. Thanks for the bug report. :)

**Comment by Datseris** [comment] 2022-06-13 15:54
Was there anything breaking? Notice that `0.0.x` releases are always considered breaking. On the other hand, `0.1.x` releases are not considered breaking when increasing `x`. cf: https://github.com/JuliaDynamics/InteractiveDynamics.jl/pull/97

**Comment by fbanning** [comment] 2022-06-13 18:29
Nope, no breaking changes for `InteractiveDynamics`.

**Comment by Datseris** [comment] 2022-07-04 21:33
closed in `main` branch.

**Closed by Datseris** 2022-07-04 21:33 UTC
Labels: open street map
